# Generated by Django 4.2.1 on 2023-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirts'), ('dress', 'Dress'), ('pants', 'Pants'), ('accessory', 'Accessory')], default='shirt', max_length=15),
        ),
    ]
