# Generated by Django 4.2.1 on 2023-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0003_alter_clothing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirts'), ('dress', 'Dress'), ('pants', 'Pants'), ('accessory', 'Accessory')], default='shirt', max_length=15),
        ),
    ]
