# Generated by Django 4.2.1 on 2023-06-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_outfit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outfit',
        ),
    ]
