# Generated by Django 4.2.1 on 2023-07-01 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wardrobe', '0009_delete_mergedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='description',
        ),
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.CharField(choices=[('headwear', 'Headwear'), ('neckwear', 'Neckwear'), ('top', 'Top'), ('bottom', 'Bottom'), ('legwear', 'Legwear'), ('feetwear', 'Feetwear'), ('underwear', 'Underwear'), ('underwear', 'Accessory'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='clothing_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
